package vct.rewrite.csimplifier

import com.typesafe.scalalogging.LazyLogging
import vct.col.ast._
import vct.col.origin.PanicBlame
import vct.col.rewrite.{Generation, Rewriter, RewriterBuilder}

case object RestoreCArrays extends RewriterBuilder {
  override def key: String = "restoreCArrays"

  override def desc: String =
    "Turn pointers generated by VerCors' internal array representation back into C arrays"
}

case class RestoreCArrays[Pre <: Generation]()
    extends Rewriter[Pre] with LazyLogging {
  outer =>

  private def replaceNewNonNullArray(
      s: Seq[Statement[Pre]]
  ): Seq[Statement[Post]] = {
    s match {
      case Nil => Nil
      case (ld @ LocalDecl(v)) +:
          (a @ Assign(Local(r), NewNonNullPointerArray(t, s))) +: rem =>
        if (r.decl == v) {
          lazy val rv = v.rewrite(t =
            CTArray(Some(dispatch(s)), dispatch(t))(PanicBlame(
              "Array Size error"
            ))
          ).succeedOnly(v)
          lazy val nl = ld.rewrite(local = rv)
          nl +: replaceNewNonNullArray(rem)
        } else { Seq(dispatch(ld), dispatch(a)) ++ replaceNewNonNullArray(rem) }
      case x +: rem => dispatch(x) +: replaceNewNonNullArray(rem)
    }
  }

  override def dispatch(stat: Statement[Pre]): Statement[Post] = {
    stat match {
      case b: Block[Pre] =>
        b.rewrite(statements = replaceNewNonNullArray(b.statements))
      case _ => super.dispatch(stat)
    }
  }

}
