#ifndef VCLLVM_PUREASSIGNER_H
#define VCLLVM_PUREASSIGNER_H

#include "vct/col/ast/col.pb.h"
#include <llvm/IR/PassManager.h>
/**
 * The PureAssignerPass checks if a LLVM function is pure (i.e. whether the !VC.pure metadata node is set)
 */
namespace vcllvm {
    using namespace llvm;
    namespace col = vct::col::ast;

    class PureAssignerPass : public PassInfoMixin<PureAssignerPass> {
    private:
        std::shared_ptr<col::Program> pProgram;
    public:
        explicit PureAssignerPass(std::shared_ptr<col::Program> pProgram);

        PreservedAnalyses run(Function &F, FunctionAnalysisManager &FAM);
    };
    /**
     * Helper function to generate errors generated by this Pass
     * @param F
     * @param explanation
     */
    void reportError(Function &F, const std::string &explanation);
}
#endif //VCLLVM_PUREASSIGNER_H
