package vct.col.rewrite.adt

import vct.col.ast._
import vct.col.origin.{
  Blame,
  NoContext,
  OptionNone,
  Origin,
  PanicBlame,
  PreconditionFailed,
}
import vct.col.rewrite.{Generation, NonLatchingRewriter}
import vct.col.util.AstBuildHelpers._
import vct.col.util.Substitute

case object ImportOption extends ImportADTBuilder("option") {
  case class OptionNonePreconditionFailed(access: OptGet[_])
      extends Blame[PreconditionFailed] {
    override def blame(error: PreconditionFailed): Unit =
      access.blame.blame(OptionNone(access))
  }
}

case class ImportOption[Pre <: Generation](importer: ImportADTImporter)
    extends ImportADT[Pre](importer) {
  import ImportOption._

  private lazy val optionFile = parse("option")

  private lazy val optionAdt = find[AxiomaticDataType[Post]](
    optionFile,
    "option",
  )
  private lazy val optionNone = find[ADTFunction[Post]](optionAdt, "None")
  private lazy val optionSome = find[ADTFunction[Post]](optionAdt, "some")
  private lazy val optionAxGet = find[ADTFunction[Post]](
    optionAdt,
    "option_get",
  )
  private lazy val optionGet = find[Function[Post]](optionFile, "opt_get")
  private lazy val optionGetOrElse = find[Function[Post]](
    optionFile,
    "opt_or_else",
  )

  def optNone(t: Type[Post])(implicit o: Origin): Expr[Post] =
    ADTFunctionInvocation[Post](
      Some((optionAdt.ref, Seq(t))),
      optionNone.ref,
      Nil,
    )

  def optSome(e: Expr[Post], t: Type[Post])(implicit o: Origin): Expr[Post] =
    ADTFunctionInvocation[Post](
      Some((optionAdt.ref, Seq(t))),
      optionSome.ref,
      Seq(e),
    )

  def optGet(e: Expr[Post], t: Type[Post], blame: Blame[PreconditionFailed])(
      implicit o: Origin
  ): Expr[Post] =
    FunctionInvocation[Post](optionGet.ref, Seq(e), Seq(t), Nil, Nil)(NoContext(
      blame
    ))

  override def postCoerce(t: Type[Pre]): Type[Post] =
    t match {
      case TOption(element) => TAxiomatic(optionAdt.ref, Seq(dispatch(element)))
      case _ => super.postCoerce(t)
    }

  override def preCoerce(e: Expr[Pre]): Expr[Pre] =
    e match {
      // Two cases generated by ImportPointer
      // optGet(Select(OptEmpty(p), OptNoneTyped(_), OptSome(AsType(PointerAdd(OptGet(p), 0))))); and
      // optGet(Select(OptEmpty(p), OptNoneTyped(_), OptSome(AsType(OptGet(p)))))
      case og1 @ OptGet(
            Select(
              OptEmpty(a),
              OptNone() | OptNoneTyped(_),
              OptSome(
                as @ FunctionInvocation(
                  _,
                  Seq(
                    add @ FunctionInvocation(
                      _,
                      Seq(og2 @ OptGet(b), _),
                      _,
                      _,
                      _,
                      _,
                    )
                  ),
                  _,
                  _,
                  _,
                  _,
                )
              ),
            )
          ) if a == b =>
        preCoerce(
          FunctionInvocation(
            as.ref,
            Seq(
              FunctionInvocation(
                add.ref,
                Seq(OptGet(b)(og1.blame)(og2.o), add.args(1)),
                add.typeArgs,
                add.givenMap,
                add.yields,
                add.reveal,
              )(add.blame)(add.o)
            ),
            as.typeArgs,
            as.givenMap,
            as.yields,
            as.reveal,
          )(as.blame)(as.o)
        )
      case og1 @ OptGet(
            Select(
              OptEmpty(a),
              OptNone() | OptNoneTyped(_),
              OptSome(
                f @ FunctionInvocation(_, Seq(og2 @ OptGet(b)), _, _, _, _)
              ),
            )
          ) if a == b =>
        preCoerce(
          FunctionInvocation(
            f.ref,
            Seq(OptGet(b)(og1.blame)(og2.o)),
            f.typeArgs,
            f.givenMap,
            f.yields,
            f.reveal,
          )(f.blame)(f.o)
        )
      case OptEmpty(OptNone()) => tt
      case OptEmpty(OptSome(_)) => ff
      case OptGet(OptSome(inner)) => inner
      case OptGet(OptSomeTyped(_, inner)) => inner
      case OptGetOrElse(OptSome(inner), _) => inner
      case OptGetOrElse(OptSomeTyped(_, inner), _) => inner
      case OptSomeTyped(t, OptGet(inner))
          if inner.t.asOption.get.element == t =>
        inner
      case OptSome(OptGet(inner)) => inner
      case _ => super.preCoerce(e)
    }

  override def postCoerce(e: Expr[Pre]): Expr[Post] =
    e match {
      case OptEmpty(opt) =>
        Eq(dispatch(opt), optNone(dispatch(opt.t.asOption.get.element))(e.o))(
          e.o
        )
      case OptNone() => optNone(TNothing())(e.o)
      case OptNoneTyped(t) => optNone(dispatch(t))(e.o)
      case OptSome(element) =>
        optSome(dispatch(element), dispatch(element.t))(e.o)
      case OptSomeTyped(t, element) =>
        optSome(dispatch(element), dispatch(t))(e.o)
      case access @ OptGet(opt) =>
        optGet(
          dispatch(opt),
          dispatch(opt.t.asOption.get.element),
          OptionNonePreconditionFailed(access),
        )(e.o)
      case get @ OptGetOrElse(opt, alt) =>
        FunctionInvocation[Post](
          optionGetOrElse.ref,
          Seq(dispatch(opt), dispatch(alt)),
          Seq(dispatch(get.t)),
          Nil,
          Nil,
        )(PanicBlame("opt_or_else requires nothing."))(e.o)
      case _ => super.postCoerce(e)
    }
}
