name: Vercors wiki pdf workflow
# Only run when the wiki is updated
on: push
jobs:
  make_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - run: sudo apt install pandoc texlive-xetex
      - working-directory: util/wiki
        run: pip3 install -r requirements.txt
      - working-directory: util/wiki
        run: "git clone https://github.com/utwente-fmt/vercors.wiki.git"
      - working-directory: util/wiki
        run: "python3 ./generate_wiki_pdf.py -i vercors.wiki --html wiki.html"
      - working-directory: util/wiki
        run: ls
      - name: Set wiki pdf tag in github repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "Vercors Team"
          git config --local user.email "vercors@lists.utwente.nl"
          git tag --force wiki-generated-doc
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/utwente-fmt/vercors.git
          git push --force --tags
      - name: Create Wiki PDF release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "util/wiki/*.pdf,util/wiki/*.html"
          artifactContentType: application/pdf
          body: "These are automatically generated versions of the tutorial on the VerCors wiki. There are two artefacts of interest: the Latex/PDF version, suitable for printing, and the HTML version, suitable for offline viewing."
          name: VerCors Wiki PDF
          prerelease: true
          tag: wiki-generated-doc
          token: ${{ secrets.GITHUB_TOKEN }}
