/* Test that assume- and assert statements work with LLVM-IR that is 
 * generated by the Swift-frontend. 
 * Expected to pass. 
 * Transform with mem2reg
 */

func foo(_ a: Int, _ b: Int) -> Int {
    var tmp = a;
    /*@ assume tmp > 0; @*/
    tmp += b;
    /*@ assert tmp == a + b; @*/

    if tmp < 0 {
        tmp *= -1
    } 

    /*@ assert tmp >= 0; @*/
    return tmp;

}